### ISSUE TITLE
can't compile rotary/interrupt.ino

### ISSUE THREAD

**Issue by thijsdeschildre** [buxtronix/arduino#10]
The example doesn't compile on windows 10 with arduino 1.8.11.
So far I only spent countless hours getting a decent rotary encoder routine to work. This project highlights the issues I've had, so I would hope it would get working.

C:\Users\me\AppData\Local\Temp\cc8tAXOq.ltrans0.ltrans.o: In function `rotate':
D:\buxtronix-encoder\interrupt/interrupt.ino:29: undefined reference to `Rotary::process()'
C:\Users\me\AppData\Local\Temp\cc8tAXOq.ltrans0.ltrans.o: In function `global constructors keyed to 65535_0_interrupt.ino.cpp.o.1755':
:(.text.startup+0x60): undefined reference to `Rotary::Rotary(char, char)'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Uno.

**Comment by marcuscaisey** [comment]
Can you include the sketch that you're trying to compile?

**Comment by thijsdeschildre** [comment]
> Can you include the sketch that you're trying to compile?

Uhh I'm not modifying the example. Well, I just replaced the brackets with quotes for the library file. 
![buxtronic](https://user-images.githubusercontent.com/2645276/82668997-e4453b00-9c3a-11ea-815b-4ec38fb88cc6.png)

**Comment by marcuscaisey** [comment]
Have you added the library to the Arduino libraries directory? The Rotary directory should be copied into the `...\Documents\Arduino\libraries`

**Comment by thijsdeschildre** [comment]
Alright, I installed the library the proper way, loaded the example from examples\rotary\interrupt and now it works.
Sorry about that.
